title: Joshua Palicka # your name (or website title) here
logo: "/images/joshuapalicka-circle-smaller.png?raw=true"
description:
  
  <br> Hi! I'm a Computer Science professional with an M.S. in Computer Science from Seattle University with Data Science Proficiency. 
  My skillset includes multiple programming languages, machine learning, AI, software design, data structures, and algorithms.<br>
  
  <br>I'm currently seeking a data science career opportunity after I graduate in June and am eager to join a dynamic team 
  and contribute my skills and passion. If you know of any open positions, please feel free to reach out. I look forward 
  to making a meaningful impact in the data science community!<br>
  <br>
  <a href="https://www.linkedin.com/in/jpalicka/">View My LinkedIn Profile</a> 
  <br>
  <a href="https://github.com/joshuapalicka/">View My GitHub Profile</a>
  <p><small>Hosted on GitHub Pages &mdash; Theme by <a href="https://github.com/orderedlist">orderedlist</a></small></p>
theme: jekyll-theme-minimal
google_analytics: R226D9G6FD
